#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

function __(string $text): string
{
    return $text;
}


$server = new Swoole\Http\Server("127.0.0.1", 9501);

// Triggered when the HTTP Server starts, connections are accepted after this callback is executed
$server->on("Start", function(Swoole\Http\Server $server)
{
    echo "Server started at http://127.0.0.1:9501" . PHP_EOL;
});

// The main HTTP server request callback event, entry point for all incoming HTTP requests
$server->on('Request', function(Swoole\Http\Request $request, Swoole\Http\Response $response)
{
    $response->header("Content-Type", "text/html");
    $response->end((string) Html(
        head: Head([
            Title('Byancode'),
            Script(src: 'https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js', defer: true),
            Script('function binance() { return { message: "Hello world" } }'),
        ]),
        body: Body(
            children: Div(
                data: [
                    'name' => 'bianca',
                ],
                class: 'container',
                children: [
                    Text($request->server['request_uri'] ?? '/'),
                    Div([2,3,4], style: [
                        'color'     => 'currentColor',
                        'padding'   => '3rem',
                        'font-size' => '2rem',
                    ]),
                    Div('Hello World 1', ondblclick: 'alert("Hello World 1")'),
                    Div(
                        text: '`Hola ${name}`',
                        style: 'text-transform: capitalize',
                        onclick: 'alert("Hello World 2")'
                    ),
                    Div('Hello World 3'),
                    Input(
                        type: 'text',
                        model: 'name',
                        oninput: 'console.log(name)',
                    ),
                    Div('Hello World 4', onclick: 'alert("Hello World 4")'),
                ]
            ),
            style: 'background-color: #202124; color: #f2f2f2',
        ),
    ));
});

// Triggered when the server is shutting down
$server->on("Shutdown", function($server, $workerId)
{
    echo "Server is shutting down" . PHP_EOL;
});

// Triggered when worker processes are being stopped
$server->on("WorkerStop", function($server, $workerId)
{
    echo "Worker $workerId is stopping" . PHP_EOL;
});

$server->start();